title: "AWS Amplify Studio + Figmaハンズオン"
summary: "特別編 Amplify Studio ハンズオンで利用する手順書です。 https://awsbasics.connpass.com/event/240343/"
topics: ["awsbasics"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - setup-cloud9
  - setup-amplify
  - setup-studio
  - setup-react
  - delete
